config/routes.rb
Rails.application.routes.draw do
  root to: 'categories#index'
  resources :exams do
    resources :questions do
      get 'next', to: 'questions#next'
    end
  end
  resources :categories, except: %i(show)
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :exams, dependent: :destroy
  validates :name, presence: true
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  has_many :questions, dependent: :destroy
  belongs_to :category
  validates :time_of_category, presence: true
  validates :category, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :exam
  validates :num_of_exam, presence: true
  validates :question_path, presence: true
  validates :description_path, presence: true
  validates :exam, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i(edit update destroy)

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: %i(show edit update destroy)

  def index
    @exams = Exam.all
  end

  def show
  end

  def new
    @exam = Exam.new
  end

  def edit
  end

  def create
    @exam = Exam.new(exam_params)
    if @exam.save
      redirect_to @exam, notice: 'Exam was successfully created.'
    else
      render :new
    end
  end

  def update
    if @exam.update(exam_params)
      redirect_to @exam, notice: 'Exam was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @exam.destroy
    redirect_to exams_url, notice: 'Exam was successfully destroyed.'
  end

  private
  def set_exam
    @exam = Exam.find(params[:id])
  end

  def exam_params
    params.require(:exam).permit(:time_of_category, :category)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i(next show edit update destroy)
  before_action :set_exam

  def next
    next_question = @exam.questions.where(num_of_exam: @question.num_of_exam + 1).first
    render json: { question: next_question}
  end

  def index
    @questions = @exam.questions
  end

  def show
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to @question, notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question, notice: 'Question was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_url, notice: 'Question was successfully destroyed.'
  end

  private
  def set_question
    @question = Question.find(params[:id] || params[:question_id])
  end

  def set_exam
    @exam = Exam.find(params[:exam_id])
  end

  def question_params
    params.require(:question).permit(:num_of_exam, :question_path, :choice_path, :description_path, :exam)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
.panel.panel-info
  .panel-heading 試験一覧
  %ul.list-group
    - @categories.each do |category|
      %li.list-group-item
        = category.name
        - unless category.id == 1
          %span [準備中]
        - category.exams.each do |exam|
          - if category.id == 1
            = link_to "第#{exam.time_of_category}回", exam, class: 'link_to_exam'
          - else
            = link_to "第#{exam.time_of_category}回", "#", class: 'link_to_exam'

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/exams/_form.html.haml
= form_for @exam do |f|
  - if @exam.errors.any?
    #error_explanation
      %h2= "#{pluralize(@exam.errors.count, "error")} prohibited this exam from being saved:"
      %ul
        - @exam.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :time_of_category
    = f.number_field :time_of_category
  .field
    = f.label :category
    = f.text_field :category
  .actions
    = f.submit 'Save'

app/views/exams/edit.html.haml
%h1 Editing exam

= render 'form'

= link_to 'Show', @exam
\|
= link_to 'Back', exams_path

app/views/exams/index.html.haml
%h1 Listing exams

%table
  %thead
    %tr
      %th Time of category
      %th Category
      %th
      %th
      %th

  %tbody
    - @exams.each do |exam|
      %tr
        %td= exam.time_of_category
        %td= exam.category
        %td= link_to 'Show', exam
        %td= link_to 'Edit', edit_exam_path(exam)
        %td= link_to 'Destroy', exam, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Exam', new_exam_path

app/views/exams/new.html.haml
%h1 New exam

= render 'form'

= link_to 'Back', exams_path

app/views/exams/show.html.haml
= react_component 'QuestionView', exam: @exam, question: @exam.questions.first, classification: { category: @exam.category.name, timeOfCategory: @exam.time_of_category }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RunnersShikaku
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container-fluid
      = yield

app/views/questions/_form.html.haml
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :num_of_exam
    = f.number_field :num_of_exam
  .field
    = f.label :question_path
    = f.text_field :question_path
  .field
    = f.label :description_path
    = f.text_field :description_path
  .field
    = f.label :exam
    = f.text_field :exam
  .actions
    = f.submit 'Save'

app/views/questions/edit.html.haml
%h1 Editing question

= render 'form'

= link_to 'Show', @question
\|
= link_to 'Back', questions_path

app/views/questions/index.html.haml
%h1 Listing questions

%table
  %thead
    %tr
      %th Num of exam
      %th Question path
      %th Description path
      %th Exam
      %th
      %th
      %th

  %tbody
    - @questions.each do |question|
      %tr
        %td= question.num_of_exam
        %td= question.question_path
        %td= question.description_path
        %td= question.exam
        %td= link_to 'Show', question
        %td= link_to 'Edit', edit_question_path(question)
        %td= link_to 'Destroy', question, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/questions/new.html.haml
%h1 New question

= render 'form'

= link_to 'Back', questions_path

app/views/questions/show.html.haml
%p#notice= notice

%p
  %b Num of exam:
  = @question.num_of_exam
%p
  %b Question path:
  = @question.question_path
%p
  %b Description path:
  = @question.description_path
%p
  %b Exam:
  = @question.exam

= link_to 'Edit', edit_question_path(@question)
\|
= link_to 'Back', questions_path